#!/usr/bin/env bash
# Quick Start Script for Diablo Uma Development

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

clear

echo -e "${BLUE}╔════════════════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║        🎭 DIABLO UMA - PÁGINA REORGANIZADA ✓                  ║${NC}"
echo -e "${BLUE}╚════════════════════════════════════════════════════════════════╝${NC}"
echo ""

echo -e "${GREEN}📁 ESTRUCTURA DEL PROYECTO:${NC}"
echo ""
echo "diablo-uma/"
echo "├── 📄 index.html              ← Archivo principal"
echo "├── 📄 diablo-uma.html         ← Original (para referencia)"
echo "├── 📚 README.md               ← Documentación principal"
echo "├── 🏗️  ESTRUCTURA.md          ← Guía de archivos"
echo "├── 🏛️  ARQUITECTURA.md        ← Diagrama de módulos"
echo "├── 🧪 TESTING.md              ← Guía de testing"
echo "│"
echo "├── 📁 css/"
echo "│   └── 🎨 styles.css          ← Todos los estilos"
echo "│"
echo "└── 📁 js/"
echo "    ├── ⚙️  main.js            ← Punto de entrada"
echo "    ├── 🔥 fire-particles.js   ← Animación de fuego"
echo "    ├── 📋 modal-system.js     ← Lógica de modales"
echo "    ├── 📦 modal-data.js       ← Contenido centralizado"
echo "    └── 📷 camera.js           ← Sistema de cámara"
echo ""

echo -e "${YELLOW}✨ BENEFICIOS DE LA REORGANIZACIÓN:${NC}"
echo ""
echo "  ✓ Código LIMPIO y LEGIBLE"
echo "  ✓ Fácil MANTENER y MODIFICAR"
echo "  ✓ Módulos REUTILIZABLES"
echo "  ✓ COLABORACIÓN más fácil"
echo "  ✓ PERFORMANCE mejorado"
echo "  ✓ TESTING posible"
echo "  ✓ ESCALABILIDAD garantizada"
echo ""

echo -e "${BLUE}🚀 CÓMO USAR:${NC}"
echo ""
echo "  1. Abre en navegador:"
echo "     → file:///path/to/diablo-uma/index.html"
echo ""
echo "  2. O usa un servidor local:"
echo "     → python -m http.server 8000"
echo "     → http://localhost:8000"
echo ""
echo "  3. Lee la documentación:"
echo "     → README.md (Inicio rápido)"
echo "     → ESTRUCTURA.md (Detalles)"
echo "     → ARQUITECTURA.md (Diagrama)"
echo "     → TESTING.md (Verificación)"
echo ""

echo -e "${GREEN}📊 MÉTRICAS:${NC}"
echo ""
echo "  index.html      ~  150 líneas  (HTML puro)"
echo "  css/styles.css  ~  700 líneas  (Todos los estilos)"
echo "  js/main.js      ~   40 líneas  (Orquestador)"
echo "  js/modules      ~  400 líneas  (Funcionalidad modular)"
echo ""
echo "  ANTES: 1 archivo de 1500+ líneas 😫"
echo "  AHORA: 8 archivos especializados 😍"
echo ""

echo -e "${BLUE}🔥 CARACTERÍSTICAS INCLUIDAS:${NC}"
echo ""
echo "  ✓ Visualizador 3D con AR"
echo "  ✓ Sistema de modales interactivos"
echo "  ✓ Animación de partículas de fuego"
echo "  ✓ Captura de fotos con cámara web"
echo "  ✓ Diseño responsivo (desktop/tablet/móvil)"
echo "  ✓ Accesibilidad completa (WCAG)"
echo "  ✓ Privacidad garantizada (sin servidores)"
echo "  ✓ Colores temáticos del Diablo Uma"
echo ""

echo -e "${YELLOW}📌 PRÓXIMOS PASOS:${NC}"
echo ""
echo "  1. Abre index.html en tu navegador"
echo "  2. Verifica que todo funcione (TESTING.md)"
echo "  3. Lee ESTRUCTURA.md para entender cómo agregar features"
echo "  4. Modifica modal-data.js si quieres cambiar contenido"
echo "  5. Personaliza estilos en css/styles.css"
echo ""

echo -e "${GREEN}📝 ARCHIVOS DE DOCUMENTACIÓN:${NC}"
echo ""
echo "  README.md          → Descripción general del proyecto"
echo "  ESTRUCTURA.md      → Explicación de cada archivo"
echo "  ARQUITECTURA.md    → Diagrama de dependencias"
echo "  TESTING.md         → Cómo verificar que funciona"
echo ""

echo -e "${BLUE}🤝 ¿NECESITAS AYUDA?${NC}"
echo ""
echo "  • Lee la documentación primero (está muy detallada)"
echo "  • Revisa ARQUITECTURA.md para entender los flujos"
echo "  • Usa TESTING.md para verificar cada funcionalidad"
echo ""

echo -e "${GREEN}═══════════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}✅ ¡Tu página está lista para producción!${NC}"
echo -e "${GREEN}═══════════════════════════════════════════════════════════════${NC}"
echo ""
